version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: npm install
      - run: npm deploy
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - test
